// Put types here
export const MLB_FETCH_CUMULATIVE = 'MLB_FETCH_CUMULATIVE';
export const MLB_FETCH_CUMULATIVE_SUCCESS = 'MLB_FETCH_CUMULATIVE_SUCCESS';
export const MLB_FETCH_CUMULATIVE_FAILURE = 'MLB_FETCH_CUMULATIVE_FAILURE';
